# -*- coding: utf-8 -*-
"""
Created on 07/01/2026

@author: Lena Schmidt, lena.schmidt@ucl.ac.uk

This file contains regular expressions which define a systematic search. Lines in each cluster will be connected via "OR" searches, while clusters themselves are connected via "AND". Performance is best if your first cluster is the cluster that is likely to produce the least hits. the "NOT" cluster defines terms that must not occur in any searched entity, similar to the NOT search in ovid. 
"""
# cluster_NOT = [
#       r"([Gg]enes?|[Gg]enome|[Gg]enetic [Ee]xpression\w?)",
#       r"[Gg]ene\w* [Ee]xpression"
#   ]

cluster_1 = [
         r'2DSearch',
        r'Abstrackr',
        r'AbstractSifter',
        r'Abstract Sifter',
        r'ASReview',
        r'ASySD',
        r'AutoLit',
        r'Buhos',
        r'COVID NMA',
        r'Cadima',
        r'citationchaser',
        r'Citation Chaser',
        r'Cochrane Crowd',
        r'Cochrane RCT Classifier',
        r'Colandr',
        r'Covidence',
        r'Data Abstraction Assistant',
        r'Dedupe',
        r'Deduplicator',
        r'Deduklick',
        r'Dextr',
        r'DistillerSR',
        r'Distiller SR',
        r'Doctor Evidence',
        r'Elicit',
        r'EPPI Reviewer',
        r'Evidence Review Accelerator',
        r'FASTREAD',
        r'GAPScreener',
        r'HAWC',
        r'Health Assessment Workspace Collaborative',
        r'Integrative Approach for Automated Literature Reviews',
        r'IRIS AI AS',
        r'LaserAI',
        r'Laser AI',
        r'Leximancer',
        r'Lingo3G',
        r'litsearchr',
        r'MechaScreener',
        r'MEDLINE transpose',
        r'MeSH on demand',
        r'Meta Phill',
        r'MetaReviewer',
        r'Meta Reviewer',
        r'Methods wizard',
        r'Metta',
        r'NestedKnowledge',
        r'Nested Knowledge',
        r'NK Synthesis',
        r'NK AutoLit',
        r'OTTO SR',
        r'PaperQA',
        r'Paper QA',
        r'PaperFinder',
        r'Paper Finder',
        r'Pythia',
        r'PICOPortal',
        r'PICO portal',
        r'PolyglotSearch',
        r'Polyglot Search',
        r'PredicTER',
        r'RCT tagger',
        r'Rayyan',
        r'Research Screener',
        r'RevManHAL',
        r'revtools',
        r'Rnatlp',
        r'RobotAnalyst',
        r'Robot Analyst',
        r'RobotReviewer',
        r'Robot Reviewer',
        r'RobotSearch',
        r'Screenatron',
        r'ScholarQA',
        r'Scholar QA',
        r'"scite.ai"',
        r'Screen4Me',
        r'Screen 4 Me',
        r'SearchRefiner',
        r'Search Refiner',
        r'SESRA',
        r'SnowGlobe',
        r'SRA Deduplicator',
        r'SRA',
        r'SRA 2',
        r'Systematic Review Accelerator',
        r'SR Accelerator',
        r'SRDB PRO',
        r'"SRDB.PRO"',
        r'SWIFT Active Screener',
        r'SWIFT Review',
        r'Syras',
        r'SyRF',
        r'SysRev',
        r'SLuRp',
        r'systematic literature unifed review program',
        r'TERA',
        r'Trial2rev',
        r'Trialstreamer',
        r'VOSViewer',
        r'Voyant',
        r'WebPlotDigitizer',
        r'WebPlot Digitizer',
        r'Yale MeSH Analyzer',
        r'(systematic review( (\w+)){0,3} tool*)|(tool*( (\w+)){0,3} systematic review)',
        r'(evidence synthesis( (\w+)){0,3} tool*)|(tool*( (\w+)){0,3} evidence synthesis)',
        ]

#[SR as topic]
cluster_2= [
        r'(meta.?analys*)',
        r'cochrane review*',
        r'systematic review*',
        r'systematic overview*',
        r'literature review*',
        r'scoping review*',
        r'rapid review*',
        r'narrative review*',
        r'umbrella review*',
        r'review of reviews',
        r'overview of reviews',
        r'research synthes*',
        r'literature synthes*',
        r'evidence synthes*',
        r'evidence review*',
        r'evidence map*',
        r'evidence summar*',
        r'gap map*'
]
cluster_NOT_titles=[]
cluster_NOT_abstracts=[]