# -.*- coding: utf-8 -.*-
"""
Created on Tue Feb 11 10:49:37 2020

@author: Lena Schmidt, lena.schmidt@bristol.ac.uk

This file contains regular expressions which define a systematic search. Lines in each cluster will be connected via "OR" searches, while clusters themselves are connected via "AND". Performance is best if your first cluster is the cluster that is likely to produce the least hits. the "NOT" cluster defines terms that must not occur in any searched entity, similar to the NOT search in ovid.
"""
# cluster_NOT = [
#        r"\b([Gg]enes?|[Gg]enome|[Gg]enetic [Ee]xpression\w?)\b",
#        r"\b[Gg]ene\w.* [Ee]xpression\b"
#    ]

# gennaiml
cluster_1 = [
    r'((large|natural|generative|machine|deep learning)( (\w+)){0,3} (language|text))|((language|text)( (\w+)){0,3} (large|natural|generative|machine|deep learning))'
    r'(apple( (\w+)){0,3} siri)|(siri( (\w+)){0,3} apple)'
    r'(amazon( (\w+)){0,3} alexa)|(alexa( (\w+)){0,3} amazon)'
    r'artificial intelligence',
    r'generative AI',
    r'GenAI',
    r'LLM',
    r'language model.*',
    r'\bAI\b',
    r'ALBERT',
    r'AlexaTM',
    r'Alpaca',
    r'AlpaCare',
    r'Anthropic',
    r'Apertus',
    r'Bard',
    r'Bardeen',
    r'Behemoth',
    r'BART',
    r'BERT',
    r'Bing AI',
    r'Bing chat',
    r'BioGPT',
    r'BIOBERT',
    r'BioLinkBERT',
    r'BioMedGPT',
    r'BioMedLM',
    r'BLOOM',
    r'BloombergGPT',
    r'Camel',
    r'Cerebras.GPT',
    r'chatbot.*',
    r'ChatGPT',
    r'Chat.GPT',
    r'Chatsonic',
    r'Chinchilla',
    r'Claude',
    r'CodeGen',
    r'CODEX',
    r'DALL.E',
    r'DBRX',
    r'Deep-Seek',
    r'DeepSeek',
    r'DistilBERT',
    r'DocLLM',
    r'Dromedary',
    r'Elicit',
    r'EinsteinGPT',
    r'Ernie',
    r'Falcon',
    r'FLAN',
    r'FLANN-T5',
    r'Flan.PaLM',
    r'FuseLLM',
    r'Galactia.*',
    r'Galactica',
    r'Gemma',
    r'Gemini',
    r'Generative Fill',
    r'Copilot',
    r'GLaM',
    r'GLM.*',
    r'Google.Assistant',
    r'Google.Bard',
    r'Gopher',
    r'GPT',
    r'Grok',
    r'Hippo\b',
    r'IBM Watson',
    r'Inner-Monologue',
    r'InstrucGPT',
    r'Koala',
    r'KOSMOS',
    r'LaMDA',
    r'LLaMA.*',
    r'LongFormer',
    r'Mamba',
    r'Maverick',
    r'Med42.*',
    r'MedAlpaca',
    r'Med-PaLM',
    r'Megatron-Turing NLG',
    r'MeTaLM',
    r'Microsoft.Bing',
    r'Midjourney',
    r'Minerva',
    r'Mistral.*',
    r'Mixtral.*',
    r'MoD',
    r'MPT',
    r'MT5',
    r'NeevaAI',
    r'Nvidia',
    r'OpenAI',
    r'Open AI',
    r'OpenAssistant',
    r'\bOPT\b',
    r'ORCA',
    r'PaLM.*',
    r'Palmyra',
    r'PanGu-E',
    r'PathAI',
    r'Path AI',
    r'Perplexity.*',
    r'PubMedGPT',
    r'Pythia',
    r'Qwen.*',
    r'pre-trained transformer.*',
    r'pretrained transformer.*',
    r'RETRO',
    r'RoBERTa',
    r'SCIBERT',
    r'SlackGPT',
    r'SpanBERT',
    r'Sparrow',
    r'Stable Diffusion',
    r'StarCoder.*',
    r'StartCoder',
    r'StyleGAN',
    r'Synthesia',
    r'T5',
    r'TinyLlama',
    r'U-PaLM',
    r'Vertex',
    r'Vicuna',
    r'WebGPT',
    r'XLNet',
    r'YaLM',
    r'YouChat',
    r'Zephyr',
    r'Zhongjing',
    r'Automation',
    r'machine.{0,5}learning',
    r'natural language processing',
    r'data mining',
    r'semi.{0,5}automat.*',
    r'active.{0,5}learn.*',
    r'bidirectional encoder representation.*',
    r'causality mining',
    r'causality extraction',
    r'embedding|word2vec',
    r'classifier.*',
    r'(supervised classification|unsupervised classification|weak supervision|distant supervision|distantly supervised)',
    r'conditional random field.*|CRF',
    r'convolutional neural network.*|CNN',
    r'data mine.*|data mining.*|mined data|mining data|datamin.*',
    r'decision tree.*',
    r'deep learn.*',
    r'inference algorithm.*',
    r'information retrieval',
    r'klog',
    r'latent dirichlet allocation|LDA|topic model',
    r'learning algorithm.*',
    r'literature min.{0,5}|min.{0,5} literature',
    r'long.short.term.memory|LSTM',
    r'maximum entropy classifier|MaxEnt|Max.Ent',
    r'multi.layer.perceptron|MLP|perceptron algorithm',
    r'naive bayes|n..ve bayes',
    r'natural language processing|NLP',
    r'neural network|neural model',
    r'regular expression|regex|rule.based.learning|term recognition',
    r'knowledge[- ]?base( (\w+)){0,50} (expert|database)|(expert|database)( (\w+)){0,50} knowledge[- ]?base',
    r'ontolog(y|ies)',
    r'predictive modelling',
    r'question answering',
    r'reading comprehension',
    r'recurrent neural network|RNN',
    r'random forest',
    r'radial basis function|RBFN',
    r'relation extraction|relation mining',
    r'SPECTER',
    r'statistical relational learn',
    r'supervised learn|semisupervised learn',
    r'support vector machine|SVM',
    r'text classif|sequence classif',
    r'text analys',
    r'text mine|text mining|mining text|mined text|textmin',
    r'transfer learn',
    r'Transformer.XL',
    r'unsupervised learn|un.supervised learn',

]
# biomed texts
cluster_2 = [
    r'RCT|trial|studies|systematic reviews',
    r'((biomedical|medicine|medical|clinical|health|healthcare|evidence.based)( (\w+)){0,3} (text|texts|abstract|abstracts|literature|documents|information|articles|domain|repository|paper|question|entit.{0,5}|decision|research|vocabulary|topic.{0,5}|problem|knowledge|corpus|corpora|semantic|outcome.{0,5}))',
    r'(text.{0,5}|abstract.{0,5}|literature|document.{0,5}|information|article.{0,5}|domain|repositor.{0,5}|paper.{0,5}|question.{0,5}|entit.{0,5}|decision.{0,5}|research|vocabular.{0,5}|topic.{0,5}|problem|knowledge|corpus|corpora|semantic|outcome)( (\w+)){0,3}(biomedical|medicine|medical|clinical|health|healthcare|evidence.based)',
    r'(RCT|trial|study|studies|pubmed|medline)( (\w+)){0,3} (abstract.{0,3}|fulltext.{0,3}|full text.{0,3})'
    r'(pico.{0,5}|peco.{0,5}|abstracts|full texts)( (\w+)){0,3} (annotat.{0,3}|classif.{0,5}|label.{0,3}|identif.{0,5}|detect.{0,5}|interpret|\btag|extract.{0,5}|benchmark|recogni.{0,5})',
    r'(annotat.{0,3}|classif.{0,5}|label.{0,3}|identif.{0,5}|detect.{0,3}|interpret.{0,3}|\btag|extract.{0,5}|benchmark|recogni.{0,5})( (\w+)){0,3} (pico.{0,5}|peco.{0,5}|abstracts|full texts)'

]
###########################check .{0,5} everywhere with adjacency queries.
# data extraction
cluster_3 = [
    r'(entity|entities|sentence.{0,5}|pico.{0,5}|peco.{0,5}|element.{0,5}|abstract.{0,5}|text.{0,5}|data|dataset|concept.{0,5}|terms|document)( (\w+)){0,3} (annotat.{0,5}|classif.{0,5}|label.{0,5}|identif.{0,5}|detect.{0,5}|interpret.{0,5}|\btag|extrac.{0,5}t|benchmark|recogni.{0,5})',
    r'(annotat.{0,5}|classif.{0,5}|label.{0,5}|identif.{0,5}|detect.{0,5}|interpret.{0,5}|\btag|extrac.{0,5}t|benchmark|recogni.{0,5})( (\w+)){0,3} (.{0,5}entity|.{0,5}entities|sentence.{0,5}|pico.{0,5}|peco.{0,5}|element.{0,5}|abstract.{0,5}|text.{0,5}|data|dataset|concept.{0,5}|terms|document)',
    r'(summar.{0,5})( (\w+)){0,3} (evidence|text.{0,3}|knowledge|stud.{0,5}|paper.{0,3}|result.{0,3}|language)',
    r'(evidence|text.{0,3}|knowledge|stud.{0,5}|paper.{0,3}|result.{0,3}|language)( (\w+)){0,3} (summar.{0,5})',
    r'((evidence)( (\w+)){0,3} (triangula.{0,5}))|((triangula.{0,5})( (\w+)){0,3} (evidence))',
    r'((information)( (\w+)){0,3} (extract.{0,5}))|((extract.{0,5})( (\w+)){0,3} (information))',
    r'((automat.{0,5})( (\w+)){0,4} (extract.{0,5}))|((extract.{0,5})( (\w+)){0,4} (automat.{0,5}))',
    r'((automat.{0,5})( (\w+)){0,4} (evidence synth.{0,5}|systematic review.{0,5}))|((evidence synth.{0,5}|systematic review.{0,5})( (\w+)){0,4} (automat.{0,5}))',
    r'knowledge graph|knowledge represent'
]

cluster_merged = [
    r'(entity|entities|sentence.{0,5}|pico.{0,5}|peco.{0,5}|element.{0,5}|abstract.{0,5}|text.{0,5}|data|dataset|concept.{0,5}|terms|document)( (\w+)){0,3} (annotat.{0,5}|classif.{0,5}|label.{0,5}|identif.{0,5}|detect.{0,5}|interpret.{0,5}|\btag|extrac.{0,5}t|benchmark|recogni.{0,5})',
    r'(annotat.{0,5}|classif.{0,5}|label.{0,5}|identif.{0,5}|detect.{0,5}|interpret.{0,5}|\btag|extrac.{0,5}t|benchmark|recogni.{0,5})( (\w+)){0,3} (.{0,5}entity|.{0,5}entities|sentence.{0,5}|pico.{0,5}|peco.{0,5}|element.{0,5}|abstract.{0,5}|text.{0,5}|data|dataset|concept.{0,5}|terms|document)',
    r'(summar.{0,5})( (\w+)){0,3} (evidence|text.{0,3}|knowledge|stud.{0,5}|paper.{0,3}|result.{0,3}|language)',
    r'(evidence|text.{0,3}|knowledge|stud.{0,5}|paper.{0,3}|result.{0,3}|language)( (\w+)){0,3} (summar.{0,5})',
    r'((evidence)( (\w+)){0,3} (triangula.{0,5}))|((triangula.{0,5})( (\w+)){0,3} (evidence))',
    r'((information)( (\w+)){0,3} (extract.{0,5}))|((extract.{0,5})( (\w+)){0,3} (information))',
    r'((automat.{0,5})( (\w+)){0,4} (extract.{0,5}))|((extract.{0,5})( (\w+)){0,4} (automat.{0,5}))',
    r'((automat.{0,5})( (\w+)){0,4} (evidence synth.{0,5}|systematic review.{0,5}))|((evidence synth.{0,5}|systematic review.{0,5})( (\w+)){0,4} (automat.{0,5}))',
    r'knowledge graph|knowledge represent',

    r'RCT|trial|studies|systematic reviews',
    r'((biomedical|medicine|medical|clinical|health|healthcare|evidence.based)( (\w+)){0,3} (text|texts|abstract|abstracts|literature|documents|information|articles|domain|repository|paper|question|entit.{0,5}|decision|research|vocabulary|topic.{0,5}|problem|knowledge|corpus|corpora|semantic|outcome.{0,5}))',
    r'(text.{0,5}|abstract.{0,5}|literature|document.{0,5}|information|article.{0,5}|domain|repositor.{0,5}|paper.{0,5}|question.{0,5}|entit.{0,5}|decision.{0,5}|research|vocabular.{0,5}|topic.{0,5}|problem|knowledge|corpus|corpora|semantic|outcome)( (\w+)){0,3}(biomedical|medicine|medical|clinical|health|healthcare|evidence.based)',
    r'(RCT|trial|study|studies|pubmed|medline)( (\w+)){0,3} (abstract.{0,3}|fulltext.{0,3}|full text.{0,3})'
    r'(entity|entities|sentence.{0,5}|pico.{0,5}|peco.{0,5}|element|abstracts|text|data|dataset|concept|terms|document)( (\w+)){0,3} (annotat.{0,3}|classif.{0,5}|label.{0,3}|identif.{0,5}|detect.{0,5}|interpret|\btag|extract.{0,5}|benchmark|recogni.{0,5})',
    r'(annotat.{0,3}|classif.{0,5}|label.{0,3}|identif.{0,5}|detect.{0,3}|interpret.{0,3}|\btag|extract.{0,5}|benchmark|recogni.{0,5})( (\w+)){0,3} (entity|entities|sentence.{0,5}|pico.{0,5}|peco.{0,5}|element.{0,5}|abstracts|text|data|dataset|concept|terms|document)'

]

#####Corpors
cluster_4 = [
    r'AbstRCT',
    r'Argument Mining Dataset',
    r'Biomedical Language Understanding and Reasoning Benchmark',
    r'BLURB',
    r'CHIP 2023 Task 5',
    r'CONSORT.{0,1}TM',
    r'EBM.{0,1}Comet',
    r'EBM.{0,1}NLP',
    r'EBM.{0,1}PICO',
    r'PubMedPICO',
    r'NICTA.{0,1}PIBOSO',
    r'Evidence inference dataset',
    r'Evidence.{0,1}inference 2',
    r'Evidence.{0,1}inference 1',
    r'MS.{0,1}2',
    r'Clinical Trials for Evidence-Based Medicine in Spanish',
]

cluster_NOT_titles = []
cluster_NOT_abstracts = []
# print(cluster_1)