# -.*- coding: utf-8 -.*-
"""
Created on 07/01/2026

@author: Lena Schmidt, lena.schmidt@ucl.ac.uk

This file contains regular expressions which define a systematic search. Lines in each cluster will be connected via "OR" searches, while clusters themselves are connected via "AND". Performance is best if your first cluster is the cluster that is likely to produce the least hits. the "NOT" cluster defines terms that must not occur in any searched entity, similar to the NOT search in ovid. 
"""

#[SR as topic]
cluster_1 = [
        r'(meta.?analys.*)',
        r'cochrane review.*',
        r'systematic review.*',
        r'systematic overview.*',
        r'literature review.*',
        r'scoping review.*',
        r'rapid review.*',
        r'narrative review.*',
        r'umbrella review.*',
        r'review of reviews',
        r'overview of reviews',
        r'research synthes.*',
        r'literature synthes.*',
        r'evidence synthes.*',
        r'evidence review.*',
        r'evidence map.*',
        r'evidence summar.*',
        r'gap map.*'
        
        ]

#[LLM & genAI]
cluster_2 = [
        r'((large|natural|generative|machine|deep learning)( (\w+)){0,3} (language|text))|((language|text)( (\w+)){0,3} (large|natural|generative|machine|deep learning))'
        r'(apple( (\w+)){0,3} siri)|(siri( (\w+)){0,3} apple)'
        r'(amazon( (\w+)){0,3} alexa)|(alexa( (\w+)){0,3} amazon)'
        r'artificial intelligence',
        r'generative AI',
        r'GenAI',
        r'LLM.*',
        r'language model.*',
        r'\bAI\b',
        r'ALBERT',
        r'AlexaTM',
        r'Alpaca',
        r'AlpaCare',
        r'Anthropic',
        r'Apertus',
        r'Bard',
        r'Bardeen',
        r'Behemoth',
        r'BART',
        r'BERT',
        r'Bing AI',
        r'Bing chat',
        r'BioGPT',
        r'BIOBERT',
        r'BioLinkBERT',
        r'BioMedGPT',
        r'BioMedLM',
        r'BLOOM',
        r'BloombergGPT',
        r'Camel',
        r'Cerebras.GPT',
        r'chatbot.*',
        r'ChatGPT.*',
        r'Chat.?GPT',
        r'Chatsonic',
        r'Chinchilla',
        r'Claude?',
        r'CodeGen',
        r'CODEX',
        r'DALL-E',
        r'DBRX',
        r'Deep-Seek',
        r'DeepSeek',
        r'DistilBERT',
        r'DocLLM',
        r'Dromedary',
        r'Elicit',
        r'EinsteinGPT',
        r'Ernie',
        r'Falcon',
        r'FLAN',
        r'FLANN-T5',
        r'Flan-PaLM',
        r'FuseLLM',
        r'Galactia.*',
        r'Galactica',
        r'Gemma',
        r'Gemini',
        r'Generative Fill',
        r'Copilot',
        r'GLaM',
        r'GLM.*',
        r'Google.* Assistant',
        r'Google.* Bard',
        r'Gopher',
        r'GPT.*',
        r'Grok',
        r'Hippo',
        r'IBM Watson',
        r'Inner-Monologue',
        r'InstrucGPT',
        r'Koala',
        r'KOSMOS',
        r'LaMDA',
        r'LLaMA.*',
        r'LongFormer',
        r'Mamba',
        r'Maverick',
        r'Med42.*',
        r'MedAlpaca',
        r'Med-PaLM',
        r'Megatron-Turing NLG',
        r'MeTaLM',
        r'Microsoft.* Bing',
        r'Midjourney',
        r'Minerva',
        r'Mistral.*',
        r'Mixtral.*',
        r'MoD',
        r'MPT',
        r'MT5',
        r'NeevaAI',
        r'Nvidia',
        r'OpenAI',
        r'Open AI',
        r'OpenAssistant',
        r'OPT',
        r'ORCA',
        r'PaLM.*',
        r'Palmyra',
        r'PanGu-E',
        r'PathAI',
        r'Path AI',
        r'Perplexity.*',
        r'PubMedGPT',
        r'Pythia',
        r'Qwen.*',
        r'pre-trained transformer.*',
        r'pretrained transformer.*',
        r'RETRO',
        r'RoBERTa',
        r'SCIBERT',
        r'SlackGPT',
        r'SpanBERT',
        r'Sparrow',
        r'Stable Diffusion',
        r'StarCoder.*',
        r'StartCoder',
        r'StyleGAN',
        r'Synthesia',
        r'T5',
        r'TinyLlama',
        r'U-PaLM',
        r'Vertex',
        r'Vicuna',
        r'WebGPT',
        r'XLNet',
        r'YaLM',
        r'YouChat',
        r'Zephyr',
        r'Zhongjing'
    ]

cluster_NOT_titles=[]
cluster_NOT_abstracts=[]
#print(cluster_1)
